### PR TITLE
Update app.json

### PR DESCRIPTION
**Pull request by Elmago27310**

### CODE REVIEW

**Comment by martijnpoppen** [comment]
@Elmago27310 can you make sure it's in the same format as the current version in the latest commit?

I made some changes with missing commas etc so this new PR will revert that :)

**Comment by martijnpoppen** [comment]
Formatted locally and merged

**Comment by Elmago27310** [comment]
Hello,

how do I put corrections?

**Comment by martijnpoppen** [comment]
Hi
Easiest is:

- go to: https://github.com/Elmago27310/com.eufylife.security/settings
- click Delete this repository in the bottom. (follow instructions)
- go to https://github.com/martijnpoppen/com.eufylife.security/blob/main/app.json 
- click the pencil icon to make changes.
- now you have the latest version :)

**Comment by Elmago27310** [comment]
Hello,

I checked the files, it seems to me that it is correct.
But there is an accent missing from "Deactivated" here 

image

and I can't find it

**Comment by martijnpoppen** [comment]
Sorry I already incorparetd your changes but didn't update the app.

You can grab the latest version here: https://homey.app/nl-nl/app/com.eufylife.security/Eufy-Security/test/

**Comment by Elmago27310** [comment]
Hello,

I just sent a last version of app.json, sorry to do it in several times

image

**Comment by martijnpoppen** [comment]
Hey, did you update your file first?
there are a lot of changes and typos now. (which i already fixed)

If you follow these instructions before you edit the file would be better: https://github.com/martijnpoppen/com.eufylife.security/pull/51#issuecomment-1376940451

**Comment by Elmago27310** [comment]
I'm not familiar with githrub, do I need to go back to the last file you made available to correct it?
Because I always start from my file

**Comment by martijnpoppen** [comment]
yes as described here: https://github.com/martijnpoppen/com.eufylife.security/pull/51#issuecomment-1376940451

**Comment by Elmago27310** [comment]
ok I just did it

**Comment by martijnpoppen** [comment]
yes perfect!
merged it, will make a update to the app soon :)

**Comment by Elmago27310** [comment]
OK, great. Thanks for the experience and if you need...

**Pull request closed without merging**
